<?php

namespace Elec\ChicagoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WardRepository extends EntityRepository
{
}
